from tkinter import *

def run_game_session():
    game_session = Tk()

    title = Label(game_session, text = 'Guess Who on Python')
    title.grid(row = 0, columnspan = 5)
    
    alex = PhotoImage(file = r'characters/standard_game/Alfred.png')
    alfred = PhotoImage(file = r'characters/standard_game/Alfred.png')
    anita = PhotoImage(file = r'characters/standard_game/Anita.png')
    anne = PhotoImage(file = r'characters/standard_game/Anne.png')
    bernard = PhotoImage(file = r'characters/standard_game/Bernard.png')
    bill = PhotoImage(file = r'characters/standard_game/Bill.png')
    charles = PhotoImage(file = r'characters/standard_game/Charles.png')
    claire = PhotoImage(file = r'characters/standard_game/Claire.png')
    david = PhotoImage(file = r'characters/standard_game/David.png')
    eric = PhotoImage(file = r'characters/standard_game/Eric.png')
    frans = PhotoImage(file = r'characters/standard_game/Frans.png')
    george = PhotoImage(file = r'characters/standard_game/George.png')
    herman = PhotoImage(file = r'characters/standard_game/Herman.png')
    joe = PhotoImage(file = r'characters/standard_game/Joe.png')
    maria = PhotoImage(file = r'characters/standard_game/Maria.png')
    maxx = PhotoImage(file = r'characters/standard_game/Max.png')
    paul = PhotoImage(file = r'characters/standard_game/Paul.png')
    peter = PhotoImage(file = r'characters/standard_game/Peter.png')
    philip = PhotoImage(file = r'characters/standard_game/Philip.png')
    richard = PhotoImage(file = r'characters/standard_game/Richard.png')
    robert = PhotoImage(file = r'characters/standard_game/Robert.png')
    sam = PhotoImage(file = r'characters/standard_game/Sam.png')
    susan = PhotoImage(file = r'characters/standard_game/Susan.png')
    tom = PhotoImage(file = r'characters/standard_game/Tom.png')

    character_1 = Label(game_session, image = alex)
    character_1.grid(row = 1, column = 0)
    character_2 = Label(game_session, image = alfred)
    character_2.grid(row = 1, column = 1)
    character_3 = Label(game_session, image = anita)
    character_3.grid(row = 1, column = 2)
    character_4 = Label(game_session, image = anne)
    character_4.grid(row = 1, column = 3)
    character_5 = Label(game_session, image = bernard)
    character_5.grid(row = 1, column = 4)
    character_6 = Label(game_session, image = bill)
    character_6.grid(row = 1, column = 5)
    character_7 = Label(game_session, image = charles)
    character_7.grid(row = 1, column = 6)
    character_8 = Label(game_session, image = claire)
    character_8.grid(row = 1, column = 7)
    character_9 = Label(game_session, image = david)
    character_9.grid(row = 2, column = 0)
    character_10 = Label(game_session, image = eric)
    character_10.grid(row = 2, column = 1)
    character_11 = Label(game_session, image = frans)
    character_11.grid(row = 2, column = 2)
    character_12 = Label(game_session, image = george)
    character_12.grid(row = 2, column = 3)
    character_13 = Label(game_session, image = herman)
    character_13.grid(row = 2, column = 4)
    character_14 = Label(game_session, image = joe)
    character_14.grid(row = 2, column = 5)
    character_15 = Label(game_session, image = maria)
    character_15.grid(row = 2, column = 6)
    character_16 = Label(game_session, image = maxx)
    character_16.grid(row = 2, column = 7)
    character_17 = Label(game_session, image = paul)
    character_17.grid(row = 3, column = 0)
    character_18 = Label(game_session, image = peter)
    character_18.grid(row = 3, column = 1)
    character_19 = Label(game_session, image = philip)
    character_19.grid(row = 3, column = 2)
    character_20 = Label(game_session, image = richard)
    character_20.grid(row = 3, column = 3)
    character_21 = Label(game_session, image = robert)
    character_21.grid(row = 3, column = 4)
    character_22 = Label(game_session, image = sam)
    character_22.grid(row = 3, column = 5)
    character_23 = Label(game_session, image = susan)
    character_23.grid(row = 3, column = 6)
    character_24 = Label(game_session, image = tom)
    character_24.grid(row = 3, column = 7)

    machine_output = Label(game_session, text = 'machine question', background = 'red')
    machine_output.grid(row = 4, column = 0, columnspan = 8)

    turn_indicator = Label(game_session, text = 'turn')
    turn_indicator.grid(row = 5, column = 0)

    continue_button = Button(game_session, text = 'Continue...')
    continue_button.grid(row = 5, column = 6)
    continue_button = Button(game_session, text = 'Surrender :(')
    continue_button.grid(row = 5, column = 7)

    game_session.mainloop()
    pass

if __name__ == '__main__':
    run_game_session()